### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by SeanMarcia**
This fixes all the bugs and typoes I could find. I skipped Angular to be expedient.

### CODE REVIEW

**Comment by SeanMarcia** [comment]
Also, can I get commit and heroku access? :)

**Comment by SeanMarcia** [comment]
Closes #102

**Comment by bglusman** [comment]
@nevern02 Hey man, I spoke to Sean about this last night, was going to merge it just now, but if you want to look over and deploy/add Sean that's cool... I don't know/remember anything about current Heroku deployment (or even if one exists), and Sean said the Pathway folks never actually 'received' the app, i.e. got access and setup, correct @SeanMarcia ?  So I was going to merge and just push up to a fresh heroku instance today, but will wait a while to hear from you Brandon.

**Comment by nevern02** [comment]
I wasn't aware that they never received the final release. Granted, I should have been more on top of it after Ruby for Good than I was. There is an existing production deployment at https://pathway-homes.herokuapp.com/

I'll take care of adding Sean as a committer, and I'll see if I have access to add him as a deployer on Heroku.

**Comment by nevern02** [comment]
Apparently I can't add collaborators to the repo. @alindeman can you take care of that?  @SeanMarcia if you DM me the email you use on Heroku I'll add you as a deployer. Hit me up on Twitter or email me brandon@blrice.net.

**Comment by alindeman** [comment]
Yes! No problem. Or I can move it to an organization. What do you all think?

**Comment by bglusman** [comment]
I'd say an organization might be ideal if a new team takes over the app next R4G or something, is that the only way to make anyone else a full owner who's able to add other committers?  I guess it probably is, it'd be nice for the someone at organization to have that ability, so if that's only way I'd say yes.

**Comment by alindeman** [comment]
@SeanMarcia @bglusman OK, great :+1: Do you think it should be named something like `pathwayhomes` or more broad like `rubyforgood` ?

**Comment by bglusman** [comment]
@alindeman though I'd been thinking pathway-homes, now that you mention it rubyforgood seems like a good starting place for now so we can a) spotlight projects that come out of/are worked on at rubyforgood, and b) have a central place to look for and manage ownership of rubyforgood projects.  I think organizations can assign owners to individual repos, so we can make someone from pathway homes an owner of this, and as an organization they don't seem likely to have many other github projects any time soon, so that's my vote.  @SeanMarcia and @csexton should probably be owners of the org, so it's mostly their call but I'd vote yes on that.

**Comment by csexton** [comment]
It is about time we made a github org, so I threw that up for you guys :smile: :heart: 

https://github.com/rubyforgood

This is something I had always intended to set up and keep any projects we've worked on at `rubyforgood` (or links to those projects if it makes more sense to host them elsewhere).

**Comment by alindeman** [comment]
@csexton @SeanMarcia :+1: :100: I have added you as collaborators to this repository. If that allows you to transfer it to the new org, go for it. If not, I am happy to email support to have them do it.

**Comment by alindeman** [comment]
Woot! This repository is now owned by the `rubyforgood` organization. :heart: :star:

**Pull request merged**
